### PR TITLE
Add Blade version

### PR DESCRIPTION
**Pull request by jessarcher**
This PR introduces a Blade version of the Bootcamp.

The introduction page has been updated so that users can now decide between using Blade or JavaScript:

image

The sidebar navigation has been updated so that the _Introduction_, _Deploying_, and _Conclusion_ links are now top-level. The two "Building Chirper with X" sections are collapsed similar to the main Laravel docs:

image

The Inertia-specific page URLs are now prefixed with `/inertia/` and the new Blade-specific pages are prefixed with `/blade/`. I have created redirects for any existing URLs that no longer exist.

The "Notifications & Events" section is special. The content is unchanged between stacks, but I wanted to keep the links under the "Build Chirper" headings for each stack. To allow for the "active" link state to work properly, the page can be accessed by both `/inertia/notifications-and-events` and `/blade/notifications-and-events` URLs, with both pointing to the same markdown file.

TODO:

* [x] Update screenshots that show JavaScript date formatting.

### CODE REVIEW

**Comment by jessarcher** [comment]
This PR depends on https://github.com/laravel/breeze/pull/189 and https://github.com/laravel/breeze/pull/191 being merged and tagged, as there were some small differences in the Blade stack.

**Comment by jessarcher** [comment]
The only issue remaining is the handling of validation failures when editing a Chirp.

Chirper has the "create" form on the same page as multiple "edit" forms, all having a `message` field. I've set up a separate error bag for "store" and "update", which fixes part of the issue, but the following issues still remain:

* The "old" data doesn't differentiate between the create form and edit forms.
* The validation errors for editing are not targeted to the specific Chirp that was edited (there can be multiple edit forms on a page).
* The edit form does not re-open when a validation error occurs.

My Blade is a little rusty, but I'm thinking I might need to incorporate the Chirp ID in the update message bag name to solve the last two issues.

As for the "old" data, I'll need to do some digging...

**Comment by Jubeki** [comment]
An idea would be to use Ajax requests and then display the result using alpinejs. (Not quite sure if that is the optimal solution, but it would also be one way to fix the problem with the `old` data).

Example:

```javascript
fetch("/posts", {
    method: "POST",
    headers: {'Content-Type': 'application/json'}, 
    body: JSON.stringify({
        message: 'the message from the input field'
    })
}).then(res => {
    console.log("Request complete! response:", res);
});
```

Some considerations to make:

- How to handle validation errors? (Probably display using x-text)
- How to handle success? (New data should be displayed)
- How to handle delete? (Probably remove the whole element from the page)

**Comment by jessarcher** [comment]
I've solved the issue by including the Chirp ID in the error bag name (e.g. `update.123`) and then only using the "old" data if the error bag contains errors.

It does feel a little bit advanced for a Bootcamp. But the only other idea I had was to deviate from the JavaScript version and put the edit forms on a separate page (i.e. `/chirps/123/edit`)

**Comment by jessarcher** [comment]
The edit form has now been moved to a separate page which simplifies things a fair bit. Really happy with this now!

**Comment by devepilef** [comment]
> The edit form has now been moved to a separate page which simplifies things a fair bit. Really happy with this now!

This was going to be my suggestion as well, as that should be easier for newer blade-specific developers to understand and deal with. Typically when learning MVC with Laravel you're focused on the RESTful endpoints, so it makes sense to reinforce that as a starting point that can be updated later with a Livewire version or something. Great choice @jessarcher 👍🏻

**Pull request merged**
