### PR TITLE
Minor fixes in docs

### PR DESCRIPTION
**Pull request by jamiemcd**
This pull request is to fix some minor typos in the instructions I found while going through the bootcamp for the first time. No actual code to be entered by the student was modified.

1. **Deleting Chirps – Authorization** referenced `destroy` method rather than `delete` method in all three bootcamps.
2. **Creating Chirps** reference to `chirp.create` component should be `chirps.create` in the livewire bootcamp.
3. **Editing Chirps** reference to `chirp.list` component should be `chirps.list` in the livewire bootcamp.
4. **Notifications & Events – Creating the notification** for livewire referenced a nonexistent `store` method in the controller. However it should be the `store` action in the `chirps.create` component.  This required separating the `notifications-and-events.md` from a single file into three.  

Regarding issue 4, here is the text for the three bootcamps. Notice that the text for livewire has been updated while the text for blade and inertia is unchanged.

**Blade and Inertia**
> We could send the notification directly from the `store` method on our `ChirpController` class, but that adds more work for the controller, which in turn can slow down the request, especially as we'll be querying the database and sending emails.

**Livewire**
> We could send the notification directly from the `store` action on our `chirps.create` component, but that adds more work for the action, which in turn can slow down the request, especially as we'll be querying the database and sending emails.

If you would rather not have separate files, an alternative solution would be to keep the single file but change the text to something like:

> We could send the notification directly from the `store` method on our `ChirpController` class (or if using Livewire, the `store` action in the `chirps.create` component). However that adds more work for the controller, which in turn can slow down the request, especially as we'll be querying the database and sending emails.

### CODE REVIEW

**Comment by jessarcher** [comment]
Thanks @jamiemcd, looks good!

I'm in two minds about splitting the Notifications page to vary one sentence, but I think it creates a better experience for the reader. I appreciate the alternative suggestion and the atomic commits!

**Review by jessarcher — APPROVED** [review]

**Comment by taylorotwell** [comment]
I also wonder if we can avoid splitting the page just for that sentence. 🤔

**Comment by jamiemcd** [comment]
Thank you both for reviewing the PR. Yes, I've come to agree the one sentence does not really rise to the level of needing to separate the pages (and any future maintenance cost of that). 

What are your thoughts on these three alternate solutions?

1. Discard the changes to `notifications-and-events.md` in this pull request. If the student in the Livewire bootcamp wonders about the sentence:

> We could send the notification directly from the store method on our ChirpController class, but that adds more work for the controller, which in turn can slow down the request, especially as we'll be querying the database and sending emails.

We just assume if they have progressed through the Livewire bootcamp they now understand that Livewire had them code a `store()` action in the component instead of in the controller like they did in the Blade bootcamp.  It could be a lightbulb moment.

2. Have the `notifications-and-events.md` page as one file but change the following:

> We could send the notification directly from the `store` method on our `ChirpController` class (or if using Livewire, the `store` action in the `chirps.create` component). However that adds more work for the controller (or component), which in turn can slow down the request, especially as we'll be querying the database and sending emails.

3. A better suggestion for the text above? (I am new to Laravel myself.)

**Comment by jessarcher** [comment]
How's this?

> We could send the notification during the request lifecycle when creating the Chirp; however, sending email can be slow, which slows our application's response time.

**Pull request closed without merging**
